# 베이스 이미지 설정
FROM ubuntu:latest

#사용자 입력 요청 무시
ARG DEBIAN_FRONTEND=noninteractive

# 필요한 소프트웨어 패키지 설치
RUN apt-get update && \
    apt-get -y install apache2 php libapache2-mod-php php-mysql mariadb-server vim iputils-ping

#php 환경 설정
RUN sed -i 's/;extension=mysqli/extension=mysqli/g' /etc/php/*/apache2/php.ini
RUN sed -i 's/display_errors = Off/display_errors = On/g' /etc/php/*/apache2/php.ini

# MariaDB 데이터베이스 설정
RUN service mariadb start && \
    mysql -e "CREATE DATABASE think CHARACTER SET utf8;" && \
    mysql -e "CREATE USER 'tunaf'@'localhost' IDENTIFIED BY 'qwe123';" && \
    mysql -e "GRANT ALL PRIVILEGES ON think.* TO 'tunaf'@'localhost';" && \
    mysql -e "FLUSH PRIVILEGES;" && \
    mysql -e "USE think; \
    create table think_board(\
	id int not null auto_increment,\
	title varchar(300) not null,\
	description varchar(300) not null,\
	author varchar(30) not null,\
	created datetime not null,\
	file_real varchar(50),\
 	primary key(id)\
    )DEFAULT CHARACTER SET UTF8;\
    create table think_member(\
	idx int not null auto_increment,\
	name varchar(100) not null,\
	id varchar(20) not null,\
	password varchar(30) not null,\
	email varchar(30) not null,\
	position varchar(20) not null,\
	primary key(idx)\
    )DEFAULT CHARACTER SET UTF8;"\
    mysql -e "insert into think_member(name,id,password,email,position) value('admin','admin','admin','admin@admin','admin');"

#apache2 설정
RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf

# source file 복사
RUN rm -rf /var/www/html
COPY ./html /var/www/html
RUN chmod 777 /var/www/html/cookie
RUN chmod 777 /var/www/html/upload

# 포트 설정
EXPOSE 80

# 컨테이너 실행 시 실행할 명령어 설정
CMD service mariadb start && /usr/sbin/apache2ctl -D FOREGROUND